import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
const inter=Inter({
  subsets:['latin'],
  weight:['400','600','700']
})



export const metadata = {
  title: "Portfolio Sewar AlAli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
     
      <body
        className={`${inter.className} antialiased grid_background`}
      >
        <Navbar/>
         
          {children}
        <Footer/>
      </body>
    </html>
  );
}
